<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<a href="index.php">volver</a><br>
    haz register:
    <form action="index.php?c=user" method="POST">
        <input type="text" name="username" placeholder="introduce tu nombre">
        <br>
        <input type="password" name="password" placeholder="introduce tu contraseña">
        <br>
        <input type="password" name="password2" placeholder="confirma tu contraseña">
        <br>
        <input type="submit" name="register" value="Registrarse">
    </form>
</body>
</html>