<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<a href="index.php">volver</a><br>
    haz register:
    <form action="index.php?c=user" method="POST">
        <input type="text" name="name" placeholder="nombre" required>
        <input type="email" name="email" placeholder="email" required>
        <input type="password" name="password" placeholder="contraseña" required>
        <input type="password" name="password2" placeholder="confirmar contraseña" required>
        <input type="submit" name="register" value="registrarse">
</form>
</body>
</html>